export const IMPORT_FILE_TEST = 'IMPORT_FILE_TEST';
export const IMPORT_FILE_FAIL = 'IMPORT_FILE_FAIL';
export const IMPORT_FILE_LOADING = 'IMPORT_FILE_LOADING';

export const SET_DARKMODE_OFF = 'SET_DARKMODE_OFF';
export const SET_DARKMODE_ON = 'SET_DARKMODE_ON';